export const SKUS = [
  {
    id: "PKG-001",
    name: "标准包装纸箱",
    category: "包装耗材",
    stock: 1920,
    min: 500,
    color: "#bd8d55",
    location: "A-01",
    unit: "件",
    pallet: 24,
  },
  {
    id: "STO-020",
    name: "蓝色周转箱",
    category: "周转容器",
    stock: 348,
    min: 100,
    color: "#4b73d5",
    location: "A-02",
    unit: "个",
    pallet: 12,
  },
  {
    id: "PKG-048",
    name: "工业包装胶带",
    category: "包装耗材",
    stock: 2680,
    min: 600,
    color: "#d5b47a",
    location: "B-01",
    unit: "卷",
    pallet: 18,
  },
  {
    id: "PPE-010",
    name: "作业安全帽",
    category: "劳保用品",
    stock: 128,
    min: 150,
    color: "#e8b345",
    location: "B-02",
    unit: "顶",
    pallet: 16,
  },
  {
    id: "STO-012",
    name: "木质标准托盘",
    category: "周转容器",
    stock: 216,
    min: 80,
    color: "#ac8358",
    location: "C-01",
    unit: "个",
    pallet: 10,
  },
  {
    id: "PPE-036",
    name: "防护手套",
    category: "劳保用品",
    stock: 864,
    min: 200,
    color: "#799791",
    location: "C-02",
    unit: "双",
    pallet: 24,
  },
];
