export const DEMO_TRUCKS = [
  {
    id: "TRK-2051",
    plate: "沪 B·7K218",
    carrier: "昆仑元物流",
    driver: "张师傅",
    destination: "昆仑元苏州配送中心",
    shipment: "SHP-78442",
    dock: 0,
    offset: 0,
    color: "#2855ce",
    direction: "outbound" as const,
    sku: 0,
    units: 24,
  },
  {
    id: "TRK-2287",
    plate: "沪 D·6J092",
    carrier: "昆仑元供应链",
    driver: "李师傅",
    destination: "昆仑元杭州配送中心",
    shipment: "SHP-78447",
    dock: 1,
    offset: 72,
    color: "#e58440",
    direction: "inbound" as const,
    sku: 1,
    units: 12,
  },
  {
    id: "TRK-2136",
    plate: "苏 E·3N165",
    carrier: "昆仑元冷链",
    driver: "陈师傅",
    destination: "昆仑元南京配送中心",
    shipment: "SHP-78451",
    dock: 2,
    offset: 161,
    color: "#489792",
    direction: "outbound" as const,
    sku: 2,
    units: 18,
  },
];
